# tuned
# Autogenerated from man page /usr/share/man/man8/tuned.8.gz
complete -c tuned -s d -l daemon -d 'This options starts tuned as a daemon as opposed to in the foreground without…'
complete -c tuned -s D -l debug -d 'Sets the highest logging level'
complete -c tuned -s h -l help -d 'Show this help'
complete -c tuned -s l -l log -d 'Log to the file LOG.  If no LOG file is specified /var/log/tuned/tuned'
complete -c tuned -l no-dbus -d 'Do not attach to DBus'
complete -c tuned -s P -l pid -d 'Write process ID to the PID file'
complete -c tuned -s p -l profile -d 'Tuning profile to be activated.  It will override other settings (e. g'
complete -c tuned -s v -l version -d 'Show version information.  FILES'

