#!/usr/bin/env bash
confDir="${confDir:-${XDG_CONFIG_HOME:-$HOME/.config}}"
sourceDir="$confDir/wallbash/theme.wallbash"
targetDir="$confDir/hypr/hyprland/decorations/wallbash.conf"

rm -rf $targetDir
cat <<EOF >> "$confDir/hypr/hyprland/decorations/wallbash.conf"
# //--=Auto Generated by Wallbash---

# // -------------------------------

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 1

    col.active_border = rgba(\$wallbash_pry4ff) rgba(\$wallbash_4xa1ff) 45deg
    col.inactive_border = rgba(\$wallbash_pry1ff) rgba(\$wallbash_pry2ff) 45deg
    resize_on_border = true

    no_focus_fallback = true
    allow_tearing = true
    layout = dwindle

    snap {
        enabled = true
        window_gap = 4
        monitor_gap = 6
        respect_gaps = true
    }
}

group {
    col.border_active = rgba(\$wallbash_pry4ff) rgba(\$wallbash_4xa1ff) 45deg
    col.border_inactive = rgba(\$wallbash_pry1cc) rgba(\$wallbash_pry2cc) 45deg
    col.border_locked_active = rgba(\$wallbash_txt3ff) rgba(\$wallbash_txt4ff) 45deg
    col.border_locked_inactive = rgba(\$wallbash_txt1cc) rgba(\$wallbash_txt2cc) 45deg
}

# // -------------------------------
EOF

declare -A wallbash
while IFS='=' read -r key val; do
    [[ -z "$key" || -z "$val" ]] && continue
    val="${val#\#}"
    wallbash["$key"]="$val"
done < "$sourceDir"

sed -i "s|col.active_border = .*|col.active_border = rgba(${wallbash[wallbash_pry4]}ff) rgba(${wallbash[wallbash_4xa1]}ff) 45deg|g" "$targetDir"
sed -i "s|col.inactive_border = .*|col.inactive_border = rgba(${wallbash[wallbash_pry1]}ff) rgba(${wallbash[wallbash_pry2]}ff) 45deg|g" "$targetDir"

sed -i "s|col.border_active = .*|col.border_active = rgba(${wallbash[wallbash_pry4]}ff) rgba(${wallbash[wallbash_4xa1]}ff) 45deg|g" "$targetDir"
sed -i "s|col.border_inactive = .*|col.border_inactive = rgba(${wallbash[wallbash_pry1]}cc) rgba(${wallbash[wallbash_pry2]}cc) 45deg|g" "$targetDir"

sed -i "s|col.border_locked_active = .*|col.border_locked_active = rgba(${wallbash[wallbash_txt3]}ff) rgba(${wallbash[wallbash_txt4]}ff) 45deg|g" "$targetDir"
sed -i "s|col.border_locked_inactive = .*|col.border_locked_inactive = rgba(${wallbash[wallbash_txt1]}cc) rgba(${wallbash[wallbash_txt2]}cc) 45deg|g" "$targetDir"

if grep -Ezq 'shadow[[:space:]]*\{[^}]*enabled[[:space:]]*=[[:space:]]*true' "$confDir/hypr/hyprland/decorations.conf"; then
    sed -i "s|color = .*|color = rgba(${wallbash[wallbash_pry1]}cc)|g" "$confDir/hypr/hyprland/decorations.conf"
else
    :
fi
hyprctl reload
echo "[Wallbash] Hyprland Color Generation Completed."
