# walforgen.dcol -- generated by wallbash_bootstrap.sh
# Format (human): $dcol.rrggbb.N   #RRGGBB
$dcol.rrggbb.1   #1B1C29
$dcol.rrggbb.2   #FFFFFF
$dcol.rrggbb.3   #0A0A0C
$dcol.rrggbb.4   #0D0D10
$dcol.rrggbb.5   #0F0F12
$dcol.rrggbb.6   #121215
$dcol.rrggbb.7   #141417
$dcol.rrggbb.8   #18181C
$dcol.rrggbb.9   #1D1D21
$dcol.rrggbb.10   #1E1E22
$dcol.rrggbb.11   #212123
$dcol.rrggbb.12   #252635
$dcol.rrggbb.13   #FFFFFF
$dcol.rrggbb.14   #0D0D10
$dcol.rrggbb.15   #111214
$dcol.rrggbb.16   #141518
$dcol.rrggbb.17   #17181B
$dcol.rrggbb.18   #1B1B1F
$dcol.rrggbb.19   #202024
$dcol.rrggbb.20   #26262B
$dcol.rrggbb.21   #28282C
$dcol.rrggbb.22   #2B2C2F
$dcol.rrggbb.23   #353749
$dcol.rrggbb.24   #FFFFFF
$dcol.rrggbb.25   #131316
$dcol.rrggbb.26   #19191C
$dcol.rrggbb.27   #1D1D21
$dcol.rrggbb.28   #212225
$dcol.rrggbb.29   #26262B
$dcol.rrggbb.30   #2D2E33
$dcol.rrggbb.31   #36363C
$dcol.rrggbb.32   #38393E
$dcol.rrggbb.33   #3D3D41
$dcol.rrggbb.34   #3F4053
$dcol.rrggbb.35   #FFFFFF
$dcol.rrggbb.36   #161619
$dcol.rrggbb.37   #1D1D21
$dcol.rrggbb.38   #222226
$dcol.rrggbb.39   #27272B
$dcol.rrggbb.40   #2C2D31
$dcol.rrggbb.41   #35353A
$dcol.rrggbb.42   #3F3F45
$dcol.rrggbb.43   #424247
$dcol.rrggbb.44   #47474B

# Shell variables (sourceable): dcol_rrggbb_N
set -x dcol_rrggbb_1 "#1B1C29"
set -x dcol_rrggbb_2 "#FFFFFF"
set -x dcol_rrggbb_3 "#0A0A0C"
set -x dcol_rrggbb_4 "#0D0D10"
set -x dcol_rrggbb_5 "#0F0F12"
set -x dcol_rrggbb_6 "#121215"
set -x dcol_rrggbb_7 "#141417"
set -x dcol_rrggbb_8 "#18181C"
set -x dcol_rrggbb_9 "#1D1D21"
set -x dcol_rrggbb_10 "#1E1E22"
set -x dcol_rrggbb_11 "#212123"
set -x dcol_rrggbb_12 "#252635"
set -x dcol_rrggbb_13 "#FFFFFF"
set -x dcol_rrggbb_14 "#0D0D10"
set -x dcol_rrggbb_15 "#111214"
set -x dcol_rrggbb_16 "#141518"
set -x dcol_rrggbb_17 "#17181B"
set -x dcol_rrggbb_18 "#1B1B1F"
set -x dcol_rrggbb_19 "#202024"
set -x dcol_rrggbb_20 "#26262B"
set -x dcol_rrggbb_21 "#28282C"
set -x dcol_rrggbb_22 "#2B2C2F"
set -x dcol_rrggbb_23 "#353749"
set -x dcol_rrggbb_24 "#FFFFFF"
set -x dcol_rrggbb_25 "#131316"
set -x dcol_rrggbb_26 "#19191C"
set -x dcol_rrggbb_27 "#1D1D21"
set -x dcol_rrggbb_28 "#212225"
set -x dcol_rrggbb_29 "#26262B"
set -x dcol_rrggbb_30 "#2D2E33"
set -x dcol_rrggbb_31 "#36363C"
set -x dcol_rrggbb_32 "#38393E"
set -x dcol_rrggbb_33 "#3D3D41"
set -x dcol_rrggbb_34 "#3F4053"
set -x dcol_rrggbb_35 "#FFFFFF"
set -x dcol_rrggbb_36 "#161619"
set -x dcol_rrggbb_37 "#1D1D21"
set -x dcol_rrggbb_38 "#222226"
set -x dcol_rrggbb_39 "#27272B"
set -x dcol_rrggbb_40 "#2C2D31"
set -x dcol_rrggbb_41 "#35353A"
set -x dcol_rrggbb_42 "#3F3F45"
set -x dcol_rrggbb_43 "#424247"
set -x dcol_rrggbb_44 "#47474B"
