# Shell variables
# Generated by 'wal'
wallpaper="/home/Kroni4/.cache/rofi-wallpapers/rain_girl_door.jpg"

# Special
background='#0e1321'
foreground='#c2c4c7'
cursor='#c2c4c7'

# Colors
color0='#0e1321'
color1='#4B4B54'
color2='#61606C'
color3='#3C5780'
color4='#727489'
color5='#80818E'
color6='#9896A4'
color7='#c2c4c7'
color8='#5d6272'
color9='#4B4B54'
color10='#61606C'
color11='#3C5780'
color12='#727489'
color13='#80818E'
color14='#9896A4'
color15='#c2c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
