--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Kroni4/.cache/rofi-wallpapers/rain_girl_door.jpg"

-- Special
background="#0e1321"
foreground="#c2c4c7"
cursor="#c2c4c7"

-- Colors
color0="#0e1321"
color1="#4B4B54"
color2="#61606C"
color3="#3C5780"
color4="#727489"
color5="#80818E"
color6="#9896A4"
color7="#c2c4c7"
color8="#5d6272"
color9="#4B4B54"
color10="#61606C"
color11="#3C5780"
color12="#727489"
color13="#80818E"
color14="#9896A4"
color15="#c2c4c7"
