# Shell variables
# Generated by 'wal'
wallpaper="/home/Kroni4/Pictures/wallpapers/3 rain_world.png"

# Special
background='#150915'
foreground='#c4c1c4'
cursor='#c4c1c4'

# Colors
color0='#150915'
color1='#382667'
color2='#4B315F'
color3='#624D69'
color4='#856671'
color5='#5B3887'
color6='#6A5395'
color7='#c4c1c4'
color8='#6c586c'
color9='#382667'
color10='#4B315F'
color11='#624D69'
color12='#856671'
color13='#5B3887'
color14='#6A5395'
color15='#c4c1c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
