--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Kroni4/Pictures/wallpapers/3 rain_world.png"

-- Special
background="#150915"
foreground="#c4c1c4"
cursor="#c4c1c4"

-- Colors
color0="#150915"
color1="#382667"
color2="#4B315F"
color3="#624D69"
color4="#856671"
color5="#5B3887"
color6="#6A5395"
color7="#c4c1c4"
color8="#6c586c"
color9="#382667"
color10="#4B315F"
color11="#624D69"
color12="#856671"
color13="#5B3887"
color14="#6A5395"
color15="#c4c1c4"
